import HeadNext from "next/head";

const Head = () => {
  return (
    <HeadNext>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </HeadNext>
  );
};

export default Head;
